arch: ppc64le
language: go

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=ppc64el] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

services:
  - docker

go:
  - "1.13.x"

env:
  - IMAGE_REGISTRY=quay.io/rh-marketplace DOCKER_BUILDKIT=1

jobs:
  include:
    - stage: test
      script: 
              - docker --version
              - docker build --build-arg ARCH=ppc64le -t "quay.io/rh-marketplace/golang-base:1.15" -f build/base.Dockerfile .
              - docker build -t "public-image-registry.apps-crc.testing/symposium/redhat-marketplace-metric-state:1.0.4" -f build/metricState.Dockerfile .
              - docker build -t "public-image-registry.apps-crc.testing/symposium/redhat-marketplace-reporter:1.0.4" -f build/reporter.Dockerfile .
              - docker build -t "public-image-registry.apps-crc.testing/symposium/redhat-marketplace-authcheck:1.0.4" -f build/authcheck.Dockerfile .
              - docker build -t "public-image-registry.apps-crc.testing/symposium/redhat-marketplace-operator:1.0.4" -f build/Dockerfile .
              - make test-ci-unit