{{- $postfix := "" }}
{{- $namespace := .Values.namespace | default "openshift-redhat-marketplace" }}
{{- range .Values.roles }}
{{- $role := . }}
{{- $roleKind := "ClusterRoleBinding"}}
{{- if eq $role.type "Role" }}
{{- $roleKind = "RoleBinding" }}
{{- end }}
{{- if eq $roleKind "ClusterRoleBinding" }}
{{- $postfix = $.Values.devpostfix }}
{{- end }}
kind: {{ $roleKind }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rhm-{{ $role.name }}-binding{{ $postfix }}
  {{- if eq $role.type "Role" }}
  namespace: {{ $role.namespace | default $namespace }}
  {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ $role.serviceAccountName }}
  namespace: {{ $namespace }}
roleRef:
  kind: {{ $role.type }}
  name: {{ $role.name }}{{ $postfix }}
  apiGroup: rbac.authorization.k8s.io
---
{{- end  }}

